### ISSUE TITLE
Action does not work. Always creates comment with "Merging this branch will not change overall coverage"

### ISSUE THREAD

**Issue by piotrowski** [fgrosse/go-coverage-report#21]
![image](https://github.com/fgrosse/go-coverage-report/assets/22003852/c5e72973-63fb-49f0-a7b0-91b9f81c8156)

Hello! I decided to try your Action, unfortunatelly for some reason it always shows `0` on every touched file.

This is how I am using your action. I have this 3 steps in 1 job:
```
      - name: generate test coverage
        run: go test -cover -coverprofile=coverage.txt ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt
          retention-days: 2

      - uses: fgrosse/go-coverage-report@v1.0.0 
        if: ${{ github.event_name == 'pull_request' }}
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.txt" 
```
