### ISSUE TITLE
Error fetching artifacts

### ISSUE THREAD

**Issue by peter-crist** [fgrosse/go-coverage-report#23]
Getting the following 403 when the script is trying to fetch the [current run coverage results](https://github.com/fgrosse/go-coverage-report/blob/7469ef95bb02bcdd817b88dc54f67099320d9f37/scripts/github-action.sh#L81):
```
Run $GITHUB_ACTION_PATH/scripts/github-action.sh "test" "7766" "9372917987"
+ gh run download 9372917987 --name=unit-test-output --dir=.github/outputs
Download code coverage results from current run
  error fetching artifacts: HTTP 403: Resource not accessible by integration
```

Current usage looks like:
```
  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    needs: 
      - inputs
      - unit-test
    steps:
      - uses: actions/checkout@v3
      - uses: fgrosse/go-coverage-report@v1.0.1
        with:
          coverage-artifact-name: unit-test-output
          coverage-file-name: ${{ inputs.project-path }}/unitcoverage.out
```

where the `unit-test` job has a successful upload:
```
      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-output
          path: |
            ${{ inputs.project-path }}/unitcoverage.out
 ```
 
 Names and paths are correct but getting a 403 on the `gh run download` call. Setup job shows:
 ```
 GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  Packages: read
  PullRequests: write
Secret source: Actions
```
